name: Generate snake animation
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate snake.svg for light mode
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rafidrahman1
          outputs: |
            dist/snake-light.svg?color_snake=333&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
      
      - name: Generate snake.svg for dark mode
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rafidrahman1
          outputs: |
            dist/snake-dark.svg?color_snake=#c6e4dd&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
      
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
